### ISSUE TITLE
Split `decryptMessage` into its own package

### ISSUE THREAD

**Issue by devceline** [WalletConnect/push-client-js#29]
Due to the needs of push message services on the web, we'll need to decrypt `push_message`s coming in. However, having the entirety of the push client will fail due to limitations of the service worker. Thus, decoupling `decryptMessage` from the engine will make it easy to import into a service worker and decrypt messages.

1. Make new package that has `decryptMessage` and only the necessities to make it work
2. Publish said package and refactor `push-client-js` to use it instead of its internal `decryptMessage`
3. Remove redundant code

**Comment by bkrem** [comment]
Resolved via #32
